### ISSUE TITLE
Docker-unit doesn't work with complex dockerfile 

### ISSUE THREAD

**Issue by xinity** [l0rd/docker-unit#1]
Hi, 

Great job about docker-unit, i've tried it with one of our dockerfile and it fails at some point. 

1) the MAINTAINER instruction isn't parse correctly and makes docker-unit fail 

2) complex command like :
RUN sed -i ......  Or ADD /src/.dotfile make docker-unit fails too

It's very promising, but parsing of a dockerfile seems rather incomplet or tricky 

Can't wait to see this project evolving to complet parsing of any dockerfile :-)

**Comment by l0rd** [comment]
@xinity thank you for opening issue #1 ! :smile:  
These are [dockeramp](https://github.com/jlhawn/dockramp) related issues but I'll have a look at it.

**Comment by xinity** [comment]
Cool ! 

Let me know if I can be of any help :-)
Merry Christmas by the way

**Comment by l0rd** [comment]
@xinity Merry Christmas :christmas_tree: ! 

I had a look at those problems :
 - I've fixed the issue with the MAINTAINER instruction
 - I cannot reproduce the issue with `RUN sed -i`. Can you please provide an instruction that does't build? The following Dockerfile works fine : 

```
FROM debian
MAINTAINER Victor Vieux <victor@docker.com>
RUN touch /tmp/foo
RUN sed -i 's/abc/def/' /tmp/foo
CMD echo "hello"
```
 - The ADD command is not supported yet. I'm opening a different issue for that (#2) since it's not related to complex Dockerfiles.

By the way thanks again and if you can do more testing on docker-unit that would help me a lot.

**Comment by xinity** [comment]
i'll test docker-unit on one of our most complex Dockerfiles to see how it goes :)

i'll let you know
